version: '3'

services:
  db:
    image: postgres
  redis:
    image: "redis:alpine"
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:80
    volumes:
      - .:/code
    ports:
      - "80:80"
    depends_on:
      - db
      - redis
  celery:
    build: .
    command: celery -A proj worker -l info -B
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
